### ISSUE TITLE
Scaling on mobile devices

### ISSUE THREAD

**Issue by midniteslice** [bpepple/thwip#7]
First off, Many, many thanks for Thwip! I really enjoyed BAMF and this looks like an awesome replacement. I really appreciate the work you've put into both applications. 

**Describe the bug**
Scaling on an android tablet or phone is no fun at all. Please see the first screenshot as an example.

**To Reproduce**
Open on mobile

**Expected behavior**
A mobile friendly interface

**Screenshots**
Before Change:
![Screenshot_20190501-154245](https://user-images.githubusercontent.com/25418291/57038712-94a76200-6c28-11e9-8d5d-0265a95c8eb6.png)
After change:
![Screenshot_20190501-154440](https://user-images.githubusercontent.com/25418291/57038726-9a9d4300-6c28-11e9-88c7-1758a7869e4c.png)

**Desktop (please complete the following information):**
 - OS: Android
 - Browser: chrome on mobile
 - Version: 73.0.3683.90

**Additional context**
I am not a developer in any way, shape, or form, but my goal was to try and find a solution before  I cried for help. That said,  I was able to get this to scale on my mobile devices by changing line 5 in public/index.html from:
`    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">`
to:
`    <meta name="viewport" content="shrink-to-fit=yes">`
It has so far worked great on my devices. I'm not sure how it affects anything else though.

**Comment by bpepple** [comment]
Moving bug to correct product, [thwip-frontend](https://github.com/bpepple/thwip-frontend/issues/6)
